'''
Verb list
Author: Michelle Burroughs
'''

verbs = {'accourir': 'come running', 'acheter': 'buy', 'adorer': 'love', 'aider': 'help', 'aimer': 'like',
         'ajouter':'add', 'aller': 'go', 'arriver': 'arriver', 'apercevoir': 'perceive', 'arreter': 'stop',
         'apporter': 'bring', 'apprendre': 'learn', 'attendre': 'watch', 'accuellir': 'welcome', 'annuler': 'cancel',
         'asseoir': 'sit', 'avaler': 'swallow', 'avancer': 'advance', 'avoir': 'have', 'avouer': 'confess',
         'appeler': 'call', 'allumer': 'light', 'accepter': 'accept', 'ameliorer': 'improve', 'analyser': 'analyse',
         'admirer': 'admire', "s'amuser": 'have fun', 'agir': 'act', 'assurer': 'assure', 'accuser': 'acuse',
         'attraper': 'catch', 'attirer': 'attract', 'se assurer': 'assure', 'assister': 'attend', 'agacer': 'annoy',
         'asseigner': 'beseige', 'asaillir': 'attack', 'arranger': 'arrange', 'approuver': 'approve',
         'approcher': 'approach', 'apprecier': 'appreciate', 'annoucer': 'annouce', 'amener': 'bring',
         'addresser': 'address', 'admettre': 'admit', 'acquierir': 'acquire', 'achever': 'achieve',
         'aacroitre': 'increase', 'accrocher': 'hang', 'accorder': 'accord', 'accompagner': 'accompany',
         'acclaimer': 'acclaim', "s'abstenir": 'abstain', 'absoudre': 'absolve', 'abolir': 'abolish',
        'abattre': 'dishearten', 'abasoudrir': 'daze', "s'abaisser": 'lower oneself',
         'baisser': 'lower', 'se battre': 'fight', 'boire': 'drink', 'se brosser': 'brush', 'bruler': 'burn',
         'blesser': 'injure', 'brancher': 'connect', 'appartenir': 'belong', 'atteindre': 'reach',
         'blaisser': 'blame', 'bouillir': 'boil', 'bouger': 'move', 'blanchir': 'whiten', 'blamer': 'blame',
         'benir': 'bless', 'bavarder': 'chat', 'batir': 'build', 'balayer': 'sweep', 'balancer': 'balance',
         'casser': 'break', 'commencer': 'start', 'contruire': 'contruct', 'convaincre': 'convince', 'courir': 'run',
         'crier': 'shout', 'continuer': 'continue', 'contenir': 'contain', 'conserver': 'conserve', 'changer': 'change',
         'creer': 'create', 'croire': 'believe', 'couper': 'cut', 'conduire': 'drive', 'conaitre': 'know',
         'contacter': 'contact', 'cacher': 'hide', 'chanter': 'sing', 'chercher': 'search', 'comprendre': 'understand',
         'consacrer': 'dedicate', 'choisir': 'choose', 'comparer': 'compare', 'consulter': 'consult',
         'completer': 'complete', 'chiffrer': 'encrypt', 'couvrir': 'cover', 'compter': 'count', 'coudre': 'sew',
         'considerer': 'consider', 'se coucher': 'go to bed', 'couter': 'cost', 'cuisiner': 'cook',
         'corrompre': 'corrupt', 'corriger': 'correct', 'convenir': 'suit', 'contredire': 'contradict',
         'constraindre': 'constrain', 'conter': 'relate', 'consentir': 'consent', 'conseiller': 'advise',
         'conquerir': 'conquer', 'conclure': 'conclude', 'concevoir': 'conceive', 'commetre': 'commit',
         'commander': 'order', 'combattre': 'combat', 'chuchoter': 'whisper', 'cherir': 'cherish', 'chasser': 'hunt',
         'charger': 'charge', 'cesser': 'cease', 'ceder': 'yield', 'causer': 'cause',
         'se depecher': 'hurry', 'detester': 'hate', 'dessiner': 'draw', 'diner': 'dine', 'donner': 'give',
         'dormir': 'sleep', 'dire': 'to say', 'se doucher': 'shower', 'diriger': 'lead', 'detruire': 'destroy',
         'debuter': 'start', 'danser': 'dance', 'desirer': 'desire', 'devoir': 'must', 'demander': 'ask',
         'dejeuner': 'lunch', 'deshabiller': 'undress', 'deviner': 'guess', 'devenir': 'become', 'decider': 'decide',
         'decouvrir': 'discover', 'decrire': 'describe', 'discuter': 'discuss', 'demenager': 'move',
         'developper': 'develop', 'descendre': 'go down', 'debarasser': 'get rid of', 'defendre': 'defend',
         'douter': 'doubt', 'deranger': 'bother',
         'ecouter': 'hear', 'enlever': 'take off', 'entendre': 'hear', "s'entrainer": 'train', 'emmener': 'bring',
         'envoyer': 'send', 'essaier': 'try', 'etre': 'be', 'etudier': 'study', 'entrer': 'enter', 'esperer': 'hope',
         'exploiter': 'exploit', 'emporter': 'carry', 'eloigner': 'remove', 'etonner': 'surprise', 'embrasser': 'hug',
         'endormir': 'fall asleep', 'epaissir': 'thicken', 'ecrire': 'write', "s'engager": 'commit','epousser': 'marry',
         'ecraser': 'crush', 'exister': 'exist', 'exiger': 'require', 'exprimer': 'express', 'eviter': 'avoid',
         'economiser': 'save', 'enterrer': 'bury', 'enfoncer': 'press in', 'expliquer': 'explain', 'excuser': 'excuse',
         'empecher': 'prevent', 'ennuyer': 'bother',
         'fabriquer': 'manufacture', 'faire': 'make', 'feter': 'celebrate', 'fermer': 'close', 'finir': 'finish',
         'fonctionner': 'operate', 'falloir': 'need', 'frapper': 'hut', 'se facher': 'get angry', 'fondre': 'melt',
         'friser': 'curl', 'fouetter': 'whip', 'figurer': 'figure',
         'geler': 'freeze', 'glisser': 'slide', 'gouter': 'taste', 'gagner': 'win', 'garder': 'keep', 'gener': 'hinder',
         'se habailler': 'dress', 'habiter': 'live', 'gerer': 'manage', 'gaspiller': 'waste', 'grandir': 'grow',
         'inviter': 'invite', 'imaginer': 'imagine', 'installer': 'settle down', 'indiquer': 'indicate',
         'inventer': 'invent', 'immigrer': 'immigrate', 'instaurer': 'establish', 'importer': 'import',
         'interoger': 'interogate',
         'jouer': 'play', 'jeter': 'throw',
         'louer': 'rent', 'laisser': 'let', 'lancer': 'throw', 'lisser': 'smooth', 'liberer': 'release',
         'se laver': 'wash', 'se lever': 'get up', 'lire': 'read', 'lister': 'list', 'lacher': 'let go',
         'manifester': 'protest', 'manger': 'eat', 'se marier': 'marry', 'mentir': 'lie', 'marcher': 'walk',
         'mettre': 'put', 'mourir': 'die', 'montrer': 'show', 'maintenir': 'maintain', 'maitriser': 'control',
         'mener': 'lead', 'marquer': 'mark', 'modifier': 'modify', 'meriter': 'earn', 'manquer': 'lack',
         'nager': 'swim', 'nettoyer': 'clean', 'naitre': 'born', 'neiger': 'snow',
         'obtenir': 'obtain', 'oser': 'dare', 'ouvre': 'open', 'organiser': 'organize', 'occuper': 'take care',
         'obeir': 'obey', 'offrir': 'offer',
         'parler': 'talk', 'peindre': 'paint', 'penser': 'think','se plaindre': 'complain', 'se plaiser': 'please',
         'pleurer': 'rain', 'porter': 'wear', 'prendre': 'take', 'presenter': 'introduce', 'se promenade': 'walk',
         'protester': 'protest', 'planter': 'plant', 'payer': 'pay', 'perdre': 'lose', 'placer': 'place',
         'prier': 'pray', 'pouvoir': 'can', 'promettre': 'promise', 'participater': 'participate', 'profiter': 'enjoy',
         'posseder': 'possess', 'pardonner': 'forgive', 'partir': 'leave', 'persuader': 'persuade', 'partager': 'share',
         'pousser': 'push', 'passer': 'spend', 'publier': 'publish', 'proteger': 'protect', 'presider': 'preside',
         'pendre': 'hang', 'preparer': 'prepare', 'permettre': 'allow', 'se perdue': 'get lost', 'poser': 'ask',
         'se placer': 'place oneself', 'prevenir': 'prevent', 'punir': 'punish', 'poursuivre': 'pursue',
         'proposer': 'propose', 'produire': 'produce', 'peser': 'weigh', 'poster': 'post',
         'quitter': 'leave',
         'ranger': 'put away', 'se raser': 'shave', 'recycler': 'recycle', 'regarder': 'watch',
         'remettre': 'put back', 'se reveiller': 'wake up', 'rever': 'dream', 'retenir': 'retain', 'retarder': 'delay',
         'recevoir': 'receive', 'renverser': 'overturn', 'retourner': 'return', 'rencontrer': 'meet', 'referer': 'refer',
         'rejoindre': 'meet', 'rayer': 'scratch', 'rire': 'laugh', 'rentre': 'return', 'rester': 'stay',
         'repousser': 'repel', 'rouger': 'blush', 'rechauffer': 'warm', 'rendre': 'make', 'revoir': 'see again',
         'raconter': 'tell', 'representer': 'represent', 'reussir': 'succeed', 'repondre': 'respond',
         'retracer': 'retrace', 'reflechir': 'reflect', 'renouveler': 'renew', 'reviser': 'revise',
         'recouvrir': 'cover', 'rater': 'miss', 'remplir': 'fill', 'ramasser': 'pick up', 'remercier': 'thank',
         'revenir': 'come back', 'rappeler': 'call back', 'reconnaitre': 'recognize', 'retrouver': 'find again',
         'risquer': 'risk', 'reprendre': 'resume', 'relever': 'raise', 'recourir': 'resort', 'reposer': 'rest',
         'sauter': 'jump', 'suivre': 'follow', 'supposer': 'think', 'soutenir': 'support', 'sembler': 'seem',
         'subir': 'put up', 'se souvenir': 'remember', 'sortir': 'get out', 'savoir': 'know', 'sourire': 'smile',
         'supplier': 'beg', 'sejourner': 'stay', 'servir': 'serve', 'signer': 'sign', 'signifier': 'signify',
         'sauver': 'save', 'souhaiter': 'wish', 'sentir': 'feel', 'saler': 'salt', 'souffrir': 'suffer',
         'suggerer': 'suggest', 'secher': 'dry',
         'tirer': 'sort', 'telephoner': 'telephone', 'tenir': 'hold', 'tromper': 'deceive', 'trouver': 'find',
         'toucher': 'touch', 'travailler': 'work', 'tourner': 'turn', 'tomber': 'fall', 'tuer': 'kill',
         'terminer': 'end', 'telecharger': 'download', 'tenter': 'tempt', 'troubler': 'confuse', 'truquer': 'fake',
         'trouer': 'make a hole', 'trotter': 'trot', 'troquer': 'swap','tumefier': 'to swell up',
         'tyranniser': 'tyrannize', 'truster': 'monopolize', 'tuyauter': 'tip off', 'trottiner': 'trot along',
         'tronquer': 'trunicate', 'troner': 'take the place of honor', 'trier': 'select','ternir': 'tarnish',
         'trancher': 'slice', 'tracer': 'trace', 'torturer': 'torture', 'tisser': 'weave', 'taxer': 'tax',
         'tester': 'test', 'terrer': 'lie low', 'tresser': 'braid', 'tricoter': 'knit', 'trainer': 'drag',
         'tramer': 'plot', 'tremper': 'soak', 'tranfuser': 'tranfuse', 'transferer': 'transfer', 'tolerer': 'tolerate',
         'utiliser': 'use', 'unifier': 'unify', 'user': 'wear out', 'uriner': 'urinate', 'urbaniser': 'urbanize',
         'uniformiser': 'uniformize', 'usurper': 'usurp', 'ululer': 'hoot', 'ulcerer': 'ulcerate',
         'vivre': 'live', 'vendre': 'sell', 'venir': 'come', 'voir': 'see', 'vouloir': 'want', 'voler': 'fly',
         'visiter': 'visit', 'voter': 'vote', 'vrombir': 'hum', 'vriller': 'spin', 'voiler': 'veil',
         'vegeter': 'vegetate', 'valoriser': 'increase value', 'vider': 'empty', 'vexer': 'annoy', 'visser': 'screw',
         'varier': 'vary', 'veiller': 'stay up', 'verbaliser': 'verbalize', 'visionner': 'view', 'vaciller': 'sway',
         'vernir': 'varnish', 'vaporiser': 'vaporize', 'virevolter': 'spin around', 'violer': 'violate',
         'vomir': 'vomit', 'vanter': 'brag', 'valser': 'waltz', 'venerer': 'venerate', 'vaguer': 'roam',
         'vagabonder': 'wander', 'vacciner': 'vaccinate', 'vadrouiller': 'roam around', 'ventiler': 'ventilate',
         'virer': 'transfer', 'viser a': 'to aim at', 'vidanger': 'empty', 'versifier': 'versify',
         'verrouiller': 'lock', 'voleter': 'flutter', 'vouer a': 'to dedicate to', 'vivoter': 'stagnate',
         'visualiser': 'visualize', 'voguer': 'sail', 'voisiner': 'to be close to', 'vivifier': 'give life to',
         'vasouiller': 'struggle', 'varapper': 'rock climb', 'vendanger': 'harvest grapes', 'verdoyer': 'be green',
         'vibrer': 'vibrate', 'violancer': 'become purple', 'vautrer': 'wallow', 'vitrer': 'install glass',
         'vulgarize': 'popularize', 'vociferer': 'yell', 'vanner': 'wear down', 'vehiculer': 'transport',
         'yodler': 'yodle',
         'zoomer': 'zoom', 'zoner': 'zone', 'zipper': 'zipper', 'zapper': 'zap', 'zezayer': 'lisp',
         'zebrer de': 'streak', 'zigzaguer': 'zigzag'}
